{
 "title": "Environmental Measurements",
 "description": "Environmental Measurements",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      (\n        r._field == \"temperature\" or\n        r._field == \"humidity\" or\n        r._field == \"voc\" or\n        r._field == \"pm25_standard\"\n      )\n    )\n  |> map(fn: (r) => ({ \n        _value: if r._field == \"temperature\" then r._value * 1.8 + 32.0 else r._value,\n        _field: r._field,\n        _time: r._time,\n        _index: \n        if r._field == \"temperature\" then 0\n        else if r._field == \"humidity\" then 1\n        else if r._field == \"voc\" then 2\n        else if r._field == \"pm25_standard\" then 3\n        else 4\n    }))\n  |> group(columns: [\"_index\"])\n  |> mean(column: \"_value\")\n"
    }
   ]
  },
  { "title": "Table View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Current Temp",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"temperature\"\n    )\n  |> map(fn: (r) => ({ \n      r with \n        _value: r._value * 1.8 + 32.0\n    }))\n  |> mean(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n |> range(start: -5m)\n |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"humidity\"\n    )\n |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n |> range(start: -5m)\n |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"voc\"\n    )\n |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "title": "AQI (I think...)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n |> range(start: -1h)\n |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"pm25_standard\"\n    )\n |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"temperature\"\n    )\n  |> map(fn: (r) => ({ r with _value: r._value * 1.8 + 32.0 }))\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: 1m, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"humidity\"\n    )\n  |> group(columns: [\"_field\"])\n |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field == \"voc\"\n    )\n  |> group(columns: [\"_field\"])\n |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => \n      r._measurement == \"air_quality\" and\n      r._field =~ /^pm.+standard$/\n    )\n  |> group(columns: [\"_field\"])\n |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  }
 ]
}